# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
