# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20170122_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
    ]
